export const Nationalities: {key:string; value:string}[] = [
    { "key": "united states", "value": "United States" },
    { "key": "china", "value": "China" },
    { "key": "india", "value": "India" },
    { "key": "brazil", "value": "Brazil" },
    { "key": "russia", "value": "Russia" },
    { "key": "nigeria", "value": "Nigeria" },
    { "key": "japan", "value": "Japan" },
    { "key": "germany", "value": "Germany" },
    { "key": "united kingdom", "value": "United Kingdom" },
    { "key": "france", "value": "France" },
    { "key": "egypt", "value": "Egypt" },
    { "key": "south africa", "value": "South Africa" },
    { "key": "australia", "value": "Australia" },
    { "key": "canada", "value": "Canada" },
    { "key": "mexico", "value": "Mexico" },
    { "key": "saudi arabia", "value": "Saudi Arabia" },
    { "key": "argentina", "value": "Argentina" },
    { "key": "italy", "value": "Italy" },
    { "key": "spain", "value": "Spain" },
    { "key": "indonesia", "value": "Indonesia" }
]